#ifndef HOOK_H
#define HOOK_H

#include <ntddk.h>

#define IOCTL_SET_HOOK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_SHARE_READ | FILE_SHARE_WRITE)
#define IOCTL_REMOVE_HOOK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_SHARE_READ | FILE_SHARE_WRITE)

NTSTATUS SetHook(PDEVICE_OBJECT DeviceObject, PIRP Irp);
NTSTATUS RemoveHook(PDEVICE_OBJECT DeviceObject, PIRP Irp);

#endif 
